version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/src/deploy
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user  
    
hooks:
  AfterInstall:
    - location: Script/deploy
      timeout: 60
#  ApplicationStart:
#    - location: Script/deploy
#      timeout: 60
